// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeBevHEN4vnvp1B88UV61cLlHo0kkrFkA',
    appId: '1:139553149732:web:2e4d73f276abc76d7dd9b1',
    messagingSenderId: '139553149732',
    projectId: 'appsmanda-203ae',
    authDomain: 'appsmanda-203ae.firebaseapp.com',
    storageBucket: 'appsmanda-203ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwXV3FU7q9-_qzvsm5q1c344nDHbo8Eyg',
    appId: '1:139553149732:android:8dfd964d500eb5297dd9b1',
    messagingSenderId: '139553149732',
    projectId: 'appsmanda-203ae',
    storageBucket: 'appsmanda-203ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqphOtvmxZmDhq2nwbwUZbKMaE89a9sk',
    appId: '1:139553149732:ios:76f05afb1042611c7dd9b1',
    messagingSenderId: '139553149732',
    projectId: 'appsmanda-203ae',
    storageBucket: 'appsmanda-203ae.firebasestorage.app',
    iosBundleId: 'com.example.newSistemInformasiSmanda',
  );
}
